# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Kai Krause
subtitle:
description:
author: Kai Krause
email: kaikrause95@gmail.com
language:
  - en
  - ja
timezone:

twitter_name: kaikrause95
disqus_shortname: kaikrause

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/blog' and root as '/blog/'
url: https://www.krausekai.com
root: /
permalink: :title/ # set post categories to: category(lang)/blog for routing # :category/:year/:title/
permalink_defaults: # set the defaults of the permalink :variables
  category: en
pretty_urls:
  trailing_index: false # whether to include .html extension in URLs

# Directory
source_dir: source
public_dir: public
tag_dir: blog/tags
#archive_dir: archives
#category_dir: categories
#code_dir: downloads/code
i18n_dir: :lang

skip_render:
  - "**.json"
  - "**.txt"

include:
  - ".gitignore"

# currently bugged
# await hexo patch
exclude:
  - "**.psd"
  - "**.afphoto"
  - "**.old"

# writing
new_post_name: :title.md # File name of new posts (will also prefix subfolder name)
default_layout: post # the default page layout as defined in the theme (e.g. post.ejs)
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0 # disable filename lower/upper-case conversion
render_drafts: false # whether to display drafts as posts
post_asset_folder: true # to source assets (images, etc) from a folder named the same as a post
relative_link: true # ??
future: true # ??

# Category & Tag
# since the category system is being used for locale
# set the default category to the default #Site 'language'
default_category: :lang
#  category_map:
#  tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
per_page: 4
pagination_dir: page # .../page/2/

blog_pagination:
  enable: true
  per_page: 4
  format: "page/%d/"

tag_pagination:
  enable: true
  per_page: 10
  format: "page/%d/"

# Atom(RSS) Feed (hexo-generator-feed)
feed:
	type: atom
	path: atom.xml
	limit: false
  hub:
  content: false
  content_limit: 140
  content_limit_delim: '...'
  order_by: -date
  icon:
  autodiscovery: true # http://www.rssboard.org/rss-autodiscovery

# Search Index (hexo-generator-search)
#	path: search.xml
#	field: post

# Themes: https://hexo.io/themes/
theme: kai-theme

# Markdown (hexo-renderer-marked)
marked:
  gfm: true
  breaks: true
  smartLists: false
  pedantic: false
  sanitize: false
  tables: false # rather use <table> syntax
  modifyAnchors: ''
  autolink: false # breaks relative embedded images

# Sitemap (hexo-generator-sitemap)
# exclude .md files by using 'sitemap: false' in front-matter
sitemap:
  path: sitemap.xml
  #tag: false
  #category: true
  template: sitemap/sitemap_template.xml

# Deployment - https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/krausekai/krausekai.github.io.git
  branch: master
